version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: banking-mongo
    ports:
      - "27017:27017"
    volumes:
      - banking_mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: banking
    restart: unless-stopped

volumes:
  banking_mongo_data:
